### PR TITLE
Example Project

### PR DESCRIPTION
**Pull request by saakethk**
ItsNous is a simple notes app that utilizes the Notion and Google Docs integrations by Endgrate.

### CODE REVIEW

**Review by WilliamHYZhang — CHANGES_REQUESTED** [review]
Missing the project, please include in subfolder

**Review by saakethk — COMMENTED** [review]
I fixed the issue. The file was identified as a submodule before.

**Review by WilliamHYZhang — CHANGES_REQUESTED** [review]
Pls remove misc. files cache, pyc, etc.

**Review by saakethk — COMMENTED** [review]
I have fixed the filename and removed miscellaneous files.

**Pull request merged**
